security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: user_account
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: user_logout
                target: homepage

    access_control:
        - { path: ^/user/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cookie/add, roles: ROLE_USER}